<a href="https://colab.research.google.com/github/arifduet/Machine-Learning-Project/blob/main/numpy_basics_to_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra


#This Session is full of Numpy From Basics to Advance

> **To Create an Numpy array**

In [ ]:
arr = np.array([1,2,3,4]) #single dimensional numpy array

In [ ]:
arr[1] #to access the data

2

In [ ]:
#Twodimensional array
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
#Multidimensional array
arr3 = np.array([
    [[1,2,3]],
    [[4,5,6]]
])

#To create an Identity Matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Basic functions in python
print("shapes of the arrays, arr :{}, arr2 : {}, arr3 : {}".format( arr.shape, arr2.shape, arr3.shape))
print()
print("dimensional of the arrays, arr :{}, arr2 : {}, arr3 : {}".format( arr.ndim, arr2.ndim, arr3.ndim ))
print()
print("size of the arrays, arr :{}, arr2 : {}, arr3 : {}".format( arr.size, arr2.size,arr3.size))

shapes of the arrays, arr :(4,), arr2 : (2, 3), arr3 : (2, 1, 3)

dimensional of the arrays, arr :1, arr2 : 2, arr3 : 3

size of the arrays, arr :4, arr2 : 6, arr3 : 6


In [ ]:
#to Find Max
print("Max number")
print(arr.max())
print(arr2.max())
print(arr3.max())
print("Index number of the maximum arguments")
#to Find the max number argument
print(arr.argmax())
print(arr2.argmax())
print(arr3.argmax())

Max number
4
6
6
Index number of the maximum arguments
3
5
5


Numpy Specials:
1) Arange Function:
np.arange(start,stop,step)

In [ ]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

2) Linspace: np.linspace(start, stop, b/n range)

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(1,10) #if range not given, it takes default value 50

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

3) logspace: np.logspace(start, stop, 10_base_range)

In [ ]:
np.logspace(1,10,4)

array([1.e+01, 1.e+04, 1.e+07, 1.e+10])

4)Ones: np.ones(num)

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

5)Zeros: np.zeros(num)

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#Random Functions in numpy


In [ ]:
np.random.rand(4) #Generates random number between 0 to 1 in the range of specified number

array([0.08312908, 0.64686741, 0.04276328, 0.60922456])

In [ ]:
np.random.randn(10) #Generates random number between Normal distributions in the range of specified number

array([ 0.24195672, -1.0426623 , -1.25304954, -0.65332846, -0.12758325,
       -0.05063112,  0.41690073,  0.50288137,  0.33752439, -1.68025534])

np.random.randint(start, stop, num) #Generates the Specified numbers from start to stop


In [ ]:
np.random.randint(1,10,4)

array([4, 4, 6, 2])

In [ ]:
np.random.random_integers(4) #Gives the random number between 1 to specified number

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 4 + 1) instead
  """Entry point for launching an IPython kernel.


3

In [ ]:
np.random.random_integers(4, size = (2,2))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 4 + 1) instead
  """Entry point for launching an IPython kernel.


array([[1, 4],
       [2, 3]])